language: java
jdk: openjdk10

install: true
script: mvn clean install
 
 script: "mvn cobertura:cobertura"


cache:
  directories:
  - $HOME/.m2
  
  
after_success:
  - bash <(curl -s https://codecov.io/bash)