language: java
jdk: openjdk10

before_install:
  - pip install --user codecov

install: true
script: mvn clean install
 
script: "mvn cobertura:cobertura"


cache:
  directories:
  - $HOME/.m2
  
  
  
after_success:
  - codecov